### ISSUE TITLE
Game Grid

### ISSUE THREAD

**Issue by dean1012** [dean1012/memes-with-friends#3]
Code needs to be designed to display the game grid (3x3) on the screen. Each grid space should be large enough to contain one Card object, the grid borders, and have some space between the Card object and grid borders for aesthetics.

**Comment by EliteTK** [comment]
Do we have a definitive idea of what the UI should look like and how it should react to user input?

I would like to sort things out so that we are not relying on a specific resolution internally (the game text looks awfully deformed when displayed on my 1366x768 laptop screen) and this shouldn't be too difficult. But to make things simple it is important to have an idea of what sort of restrictions can be imposed which would not limit future development. To understand the restrictions which can be applied we need a clear idea of what we want from the UI ranging from everything it must do to anything we might want it to do.

**Comment by dean1012** [comment]
The latest test build should give you a good idea. On the left side top Is player 1 hand. At the left side bottom is player 2 hand. Both are shown in current build.

On the empty space to the right of the screen I was going to draw the 3x3 game grid.

I was going to try to do drag and drop of the cards to the game grid but if that fails then I was going to fall back to a more static select the card then select the grid spot system.

Kebble wanted to introduce simple multiplayer but I'm not sure how that would work yet. In the absence of multiplayer I was going to make a very simple AI system.

The result of the match was going to be displayed above or below the game grid and the game would restart with another click.

Should I give you some time to refactor before continuing?

**Comment by EliteTK** [comment]
Multiplayer can be saved for later, if we're careful it won't be too hard to retrofit.

I have a patch lined up to add files to the Makefile (since new files have been added) and also another patch to replace calls to fprintfs with calls using iostream.

Drag and drop is not impossible to do, I'll look into making that possible.

If you wish to work on something, don't let me stop you, I still have to review the source to get an idea of how to deal with resizing the window. We might want to implement an event dispatcher so that handling re-sizing can be done cleanly from the get-go but I'll have a look at that too. (Maybe allegro already has something like this.)

**Comment by dean1012** [comment]
To be clear, I have no personal plans to implement multiplayer (either now or in retrofit). This was an idea strictly from Kebble. If he doesn't do it and no one else chooses to, the game will not have multiplayer. I did offer Kebble to host a server for a few months though if needed.

With that said, I think it's doable to create a basic AI for the other player to play against. This is likely the solution I will implement if no one else does.

My apologies for not keeping up with the Makefile or anything last night. From here on out, I'll make an effort to ensure I'm using iostream and adding new files to Makefile to reduce the amount of duplicate effort you have to perform.

As far as drag and drop goes, please add any thoughts you have to #10 and if you want to do it yourself, let me know and I'll assign it to you. I think it won't be hard but I wanted to reserve judgement until I tried to implement it.

If you are thinking of moving from full screen to a resizeable window (or letting users change between full screen and resizeable window with something like F11), that's fine if you can make it work. This goes well beyond my expertise so you can implement it if you wish.

Allegro has ALLEGRO_EVENT_DISPLAY_RESIZE which can be found at https://www.allegro.cc/manual/5/allegro_event

In the main while loop in main.cpp, just need to check for ALLEGRO_EVENT_DISPLAY_RESIZE and do what we need to do.

I was going to start on drawing the game grid next but it may be a day or two so if you do something first that's fine.

**Comment by dean1012** [comment]
Also note to make a resizeable window we need to use al_set_new_display_flags before creating the display as shown here https://www.allegro.cc/manual/5/al_set_new_display_flags

We specifically need to set both these flags: ALLEGRO_RESIZABLE and ALLEGRO_WINDOWED

Once that's done we can attach to the event as I described previously.

Do note that we will have to destroy the display, change flags, and recreate display to switch between windowed and full screen.

**Comment by dean1012** [comment]
Closing this issue. Will reopen a new one with less distractions in it.
