### ISSUE TITLE
Game window partially offscreen

### ISSUE THREAD

**Issue by TheTerrorByte** [dean1012/memes-with-friends#6]
Screen res: 1366x768

When running the game, the top portion of the game is shown offscreen. Window cannot be resized. Window thumbnail visible in taskbar.
![mwf4](https://cloud.githubusercontent.com/assets/8520072/26532621/596aaf50-43ba-11e7-8922-14536ee56c20.png)
![mwf3](https://cloud.githubusercontent.com/assets/8520072/26532622/596c00ee-43ba-11e7-92d5-bdb14143524d.png)

**Comment by dean1012** [comment]
This is my bad. I made the bad assumption that everyone has at least 1920x1080 so I programmed that resolution.

I'll need to switch the app to full screen instead of windowed and program it to have resolution indepdence.

I'll achieve the first part by setting the full screen flag on the display and changing the display resolution to match desktop resolution.

I'll achieve the second part by rendering everything to a virtual 1920x1080 bitmap then flipping the backbuffer to display as a scaled bitmap. In your case everything will just be a little smaller. In the case of 4K everything should be a bit bigger.
